language: python
cache: pip
python:
  - "3.6"
install:
  - pip install flake8
  - pip install -r requirements.txt
before_script:
  - flake8 maracker
  - psql -c "CREATE DATABASE maracker;" -U postgres
script:
  - cd maracker
  - python manage.py test
