

version: '2'

services:
  zoo1:
    image: zookeeper:3.4
    network_mode: "host"
    ports:
       - 2181:2181
       - 127.0.0.1:2888:2888
       - 127.0.0.1:3888:3888

  mesos-master:
    image: mesosphere/mesos-master:1.3.0
    network_mode: "host"
    environment:
      - MESOS_CLUSTER=local
      - MESOS_ZK=zk://127.0.0.1:2181/mesos
      - MESOS_HOSTNAME=127.0.0.1
      - MESOS_IP=127.0.0.1
      - MESOS_QUORUM=1
      - MESOS_CLUSTER=docker-compose
      - MESOS_WORK_DIR=/var/lib/mesos

  mesos-slave:
    image: mesosphere/mesos-slave:1.3.0
    network_mode: "host"
    privileged: true
    environment:
      - MESOS_PORT=5051
      - MESOS_MASTER=zk://127.0.0.1:2181/mesos
      - MESOS_HOSTNAME=127.0.0.1
      - MESOS_IP=127.0.0.1
      - MESOS_CONTAINERIZERS=docker,mesos
      - MESOS_WORK_DIR=/var/lib/mesos
      - MESOS_SWITCH_USER=0
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /usr/bin/docker:/usr/bin/docker.so
      - /var/run/docker.sock:/var/run/docker.sock

  marathon:
    image: mesosphere/marathon:v1.4.5
    network_mode: "host"
    ports:
      - "8080:8080"
    environment:
      - MARATHON_ZK=zk://127.0.0.1:2181/marathon
      - MARATHON_MASTER=zk://127.0.0.1:2181/mesos
      - MARATHON_HOSTNAME=127.0.0.1
      - LIBPROCESS_IP=127.0.0.1
    command: "--event_subscriber http_callback"


