version: '2'

services:
  zoo1:
    image: zookeeper:3.4
    ports:
       - 2181:2181

  mesos-master:
    image: mesosphere/mesos-master:1.3.0
    environment:
      - MESOS_CLUSTER=local
      - MESOS_ZK=zk://zoo1:2181/mesos
      - MESOS_QUORUM=1
      - MESOS_CLUSTER=docker-compose
      - MESOS_WORK_DIR=/var/lib/mesos

  mesos-slave:
    image: mesosphere/mesos-slave:1.3.0
    privileged: true
    environment:
      - MESOS_PORT=5051
      - MESOS_MASTER=zk://zoo1:2181/mesos
      - MESOS_CONTAINERIZERS=docker,mesos
      - MESOS_WORK_DIR=/var/lib/mesos
      - MESOS_SWITCH_USER=0
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /usr/bin/docker:/usr/bin/docker.so
      - /var/run/docker.sock:/var/run/docker.sock

  marathon:
    image: mesosphere/marathon:v1.4.5
    environment:
      - MARATHON_ZK=zk://zoo1:2181/marathon
      - MARATHON_MASTER=zk://zoo1:2181/mesos
    command: "--event_subscriber http_callback"
    ports:
      - 8080:8080
    labels:
       - "traefik.backend=marathon"
       - "traefik.frontend.rule=Host:ui.marathon.localhost"
       - "traefik.port=8080"

  # marathon:
  #   image: mesosphere/marathon:v1.4.5
  #   ports:
  #     - 8080:8080
  #   environment:
  #     - MARATHON_ZK=zk://zoo1:2181/marathon
  #     - MARATHON_MASTER=zk://zoo1:2181/mesos
  #   command: "--event_subscriber http_callback"

  chronos:
    image: mesosphere/chronos:v3.0.2
    ports:
      - 4400:4400
      - 8081:8081
    environment:
      - PORT0=4400
      - PORT1=8081
    command: --zk_hosts zoo1:2181 --master zk://zoo1:2181/mesos
    labels:
       - "traefik.backend=chronos"
       - "traefik.frontend.rule=Host:ui.chronos.localhost"
       - "traefik.port=4400"

  proxy:
    image: traefik:1.3-alpine
    hostname: proxy
    domainname: marathon.localhost
    volumes:
      - ./traefik.toml:/etc/traefik/traefik.toml
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8888:8888"
      - "80:80"
      - "443:443"
    command: -c /etc/traefik/traefik.toml --marathon.endpoint=http://marathon:8080
    # command: -c /etc/traefik/traefik.toml --web --logLevel=DEBUG --marathon --marathon.domain=marathon.localhost --marathon.endpoint=http://marathon:8080 --marathon.watch
