# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-05 08:55
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marackerapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mipapplication',
            name='cpu',
            field=models.DecimalField(decimal_places=1, default=0.1, max_digits=3, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
    ]
