# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 12:31
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marackerapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marathonconfig',
            name='env_vars',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, default={}),
        ),
    ]
