# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-05 08:57
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marackerapi', '0002_auto_20170605_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mipapplication',
            name='memory',
            field=models.IntegerField(default=32, validators=[django.core.validators.MinValueValidator(32)]),
        ),
    ]
