# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 12:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marackerapi', '0002_auto_20170706_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marackerapplication',
            name='docker_container',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marackerapi.DockerContainer'),
        ),
    ]
