# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-05 09:01
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marackerapi', '0003_auto_20170605_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mipapplication',
            name='docker_name',
            field=models.CharField(max_length=200, unique=True, validators=[django.core.validators.RegexValidator('\\w\\/\\w', 'The docker image name must have the following format: <namespace>/<image-name>')]),
        ),
    ]
