# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-05 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marackerapi', '0004_auto_20170605_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mipapplication',
            name='description',
            field=models.TextField(default='no description available'),
        ),
    ]
