# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-05 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marackerapi', '0006_auto_20170605_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mipapplication',
            name='docker_name',
        ),
        migrations.AddField(
            model_name='mipapplication',
            name='docker_image',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mipapplication',
            name='docker_namespace',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
