# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 20:42
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.contrib.postgres.operations import HStoreExtension


class Migration(migrations.Migration):

    dependencies = [
        ('marackerapi', '0008_auto_20170608_0952'),
    ]

    operations = [
        HStoreExtension(),
        migrations.CreateModel(
            name='CmdApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(default='no description available')),
                ('command', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DockerApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(default='no description available')),
                ('namespace', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MarathonCmd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu', models.DecimalField(decimal_places=1, default=0.1, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('memory', models.PositiveIntegerField(default=32, validators=[django.core.validators.MinValueValidator(32)])),
                ('args', models.TextField(default=None)),
                ('env_vars', django.contrib.postgres.fields.hstore.HStoreField()),
                ('cmd_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marackerapi.CmdApp')),
            ],
        ),
        migrations.CreateModel(
            name='MarathonDocker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu', models.DecimalField(decimal_places=1, default=0.1, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('memory', models.PositiveIntegerField(default=32, validators=[django.core.validators.MinValueValidator(32)])),
                ('version', models.CharField(default=None, max_length=100)),
                ('args', models.TextField(default=None)),
                ('ports', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(65535)]), size=None)),
                ('env_vars', django.contrib.postgres.fields.hstore.HStoreField()),
                ('docker_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marackerapi.DockerApp')),
            ],
        ),
        migrations.DeleteModel(
            name='MipApplication',
        ),
        migrations.AlterUniqueTogether(
            name='dockerapp',
            unique_together=set([('namespace', 'image')]),
        ),
    ]
