# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marackerapi', '0009_auto_20170625_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marathoncmd',
            name='args',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='marathondocker',
            name='args',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='marathondocker',
            name='version',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
