# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 21:37
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marackerapi', '0010_auto_20170625_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marathoncmd',
            name='env_vars',
            field=django.contrib.postgres.fields.hstore.HStoreField(default={}),
        ),
        migrations.AlterField(
            model_name='marathondocker',
            name='env_vars',
            field=django.contrib.postgres.fields.hstore.HStoreField(default={}),
        ),
    ]
