# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marackerapi', '0011_auto_20170625_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmdapp',
            name='vcs_url',
            field=models.URLField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='dockerapp',
            name='vcs_url',
            field=models.URLField(blank=True, max_length=2000),
        ),
    ]
