# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 14:39
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marackerapi', '0012_auto_20170626_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marathondocker',
            name='ports',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(65535)]), blank=True, size=None),
        ),
    ]
