# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 18:37
from __future__ import unicode_literals

import autoslug.fields
import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marackerapi', '0013_auto_20170626_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='DockerContainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('(:[\\w][\\w.]{0,127}?)?')])),
                ('ports', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(65535)]), blank=True, default=[], size=None)),
            ],
        ),
        migrations.CreateModel(
            name='MarackerApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(default='no description available')),
                ('command', models.TextField(blank=True)),
                ('vcs_url', models.URLField(blank=True, max_length=2000)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name')),
                ('docker_container', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marackerapi.DockerContainer')),
            ],
        ),
        migrations.CreateModel(
            name='MarathonConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu', models.DecimalField(decimal_places=1, default=0.1, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('memory', models.PositiveIntegerField(default=32, validators=[django.core.validators.MinValueValidator(32)])),
                ('args', models.TextField(blank=True)),
                ('env_vars', django.contrib.postgres.fields.hstore.HStoreField(default={})),
                ('maracker_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marackerapi.MarackerApplication')),
            ],
        ),
        migrations.DeleteModel(
            name='DockerApp',
        ),
        migrations.RemoveField(
            model_name='marathoncmd',
            name='cmd_app',
        ),
        migrations.RemoveField(
            model_name='marathondocker',
            name='docker_app',
        ),
        migrations.DeleteModel(
            name='CmdApp',
        ),
        migrations.DeleteModel(
            name='MarathonCmd',
        ),
        migrations.DeleteModel(
            name='MarathonDocker',
        ),
    ]
