# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marackerapi', '0014_auto_20170630_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marackerapplication',
            name='command',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='marackerapplication',
            name='description',
            field=models.TextField(blank=True, default='no description available'),
        ),
    ]
