# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marackerapi', '0018_auto_20170703_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marackerapplication',
            name='name',
            field=models.SlugField(unique=True),
        ),
    ]
